server:
  port: 8081

spring:
  application:
    name: communityfeed

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:               # ✅ Redis 설정 추가
    host: localhost    # 또는 도커 컨테이너나 외부 IP 주소
    port: 6379         # 기본 포트

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

secret-key: dG9wLXNlY3JldC1rZXktc3VwZXItdG9wLXNlY3JldC1rZXk=

fcm:
  certification: ${FIREBASE_CERT_PATH}
