server:
  port: 8081

spring:
  application:
    name: communityfeed

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000   # ⬅ DB 연결 재시도 (30초)

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


# application.yaml
secret-key: dG9wLXNlY3JldC1rZXktc3VwZXItdG9wLXNlY3JldC1rZXk=
